inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/performance.yml

require:
  - rubocop-github-annotation-formatter
  - rubocop-packaging
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
